import '../globals.css'

import type { Metadata } from 'next'
import { ReactNode } from 'react'

import { Toaster } from '@/components/ui/sonner'
import { poppinsFont } from '@/configs'

type LayoutProps = {
  children: ReactNode
  params: { locale: string }
}

export default function RootLayout({ children, params }: LayoutProps) {
  return (
    <html lang={params.locale}>
      <body className={poppinsFont.className}>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
